### 执行顺序

假设定义了两个挂起函数：

```kotlin
suspend fun doSomethingUsefulOne(): Int {
    delay(1000L)
    return 13
}

suspend fun doSomethingUsefulTwo(): Int {
    delay(1000L)
    return 29
}
```

如果我们需要按顺序调用它们，然后计算它们 的总和。在实践中，如果我们使用第一个函数的结果来决定是否需要调用第二个函数，我们一般会这么做。

我们使用普通的顺序调用，因为协程中的代码，就像在常规代码中一样，默认情况下是顺序的。以下示例通过测量执行两个挂起函数所需的总时间来演示它：

```kotlin
val time = measureTimeMillis {
    val one = doSomethingUsefulOne()
    val two = doSomethingUsefulTwo()
    println("The answer is ${one + two}")
}
println("Completed in $time ms")
```

#### 异步并发

如果`doSomethingUsefulOne`和`doSomethingUsefulTwo`的调用之间没有依赖关系，并且我们希望通过同时执行这两个操作来更快地获得答案，该怎么办？这就是`async`可以提供帮助的地方。

从概念上讲，`async`和`launch`一样。它启动一个单独的协程，这是一个与所有其它协程同时工作的轻量级线程。不同之处在于，`launch`返回一个 Job 并且不携带任何结果值，而`async`返回一个`Deferred`——一个轻量级的非阻塞，代表稍后提供结果。您可以对`Deferred`使用`.await()`以获取其最终结果，`async`也是一个作业，可以根据需求随时取消。

```kotlin
val time = measureTimeMillis {
    val one = async { doSomethingUsefulOne() }
    val two = async { doSomethingUsefulTwo() }
    println("The answer is ${one.await() + two.await()}")
}
println("Completed in $time ms")
```

这次的执行速度是两倍，因为两个协程并发执行。请注意，与协程的并发始终是显式的。

#### 延迟启动异步

异步可以通过将其启动参数设置为`CoroutineStart.LAZY`来延迟启动。在这种模式下，它仅在`await`需要其结果或调用其 Job 的`start`函数时才启动协程。运行示例如下：

```kotlin
val time = measureTimeMillis {
    val one = async(start = CoroutineStart.LAZY) { doSomethingUsefulOne() }
    val two = async(start = CoroutineStart.LAZY) { doSomethingUsefulTwo() }
    one.start()
    two.start()
    println("The answer is ${one.await() + two.await()}")
}
println("Completed in $time ms")
```

这里定义了两个协程，但是不像前面的例子那样马上执行，而是通过调用`start`将控制权交给程序员来确定何时开始执行。

请注意，如果我们只是在`println`中调用`await`而没有先在单个协程上调用`start`，这将导致顺序问题，因为`await`启动协程执行并等待其完成，这不是`Lazy`的预期使用方式。

#### 异步风格的函数

我们可以定义异步风格的函数，这些函数使用异步协程构建器异步调用`doSomethingUsefulOne`和`doSomethingUsefulTwo`，使用`GlobalScope`引用来选择退出结构化并发。我们用`...Async`后缀命名这些函数，以强调这是一个异步函数，即它们只启动异步计算，并且需要使用生成的延迟值来获取结果。

```
//返回的结果类型是Deferred<Int>
fun somethingUsefulOneAsync() = GlobalScope.async {
    doSomethingUsefulOne()
}

fun somethingUsefulTwoAsync() = GlobalScope.async {
    doSomethingUsefulTwo()
}
```

请注意这些`xxxAsync`函数不是挂起函数。它们可以在任何地方使用。然而，它们的使用总是代表并发执行操作。

一下显示了它们在协程之外的使用：

```kotlin
fun main() {
    val time = measureTimeMillis {
        //在协程之外启动异步操作
        val one = somethingUsefulOneAsync()
        val two = somethingUsefulTwoAsync()
        //但是等待结果必须涉及挂起或阻塞
        runBlocking {
            println("The answer is ${one.await() + two.await()}")
        }
    }
    println("Completed in $time ms")
}
```

此处提供这种带有异步函数的编程风格仅用于说明，因为它是其他编程语言中的流行风格。强烈建议不要在 Kotlin  协程中使用这种风格，原因如下所述。

如果`val one = somethingUsefulOneAsync()` 行和`one.await()`表达式之间代码中有一些逻辑错误，并且程序抛出异常，程序在执行中操作终止，会发生什么情况？通常，全局错误处理程序可以捕获此异常，为开发人员纪录和报告错误，但程序可以以其他方式继续执行其他操作，因此在本示例中，`somethingUsefulOneAsync`仍在后台运行，即使启动它的操作已终止。

#### 异步结构化并发

我们以结构化并发的方式来实现上述代码，首先提取一个函数，该函数总是同时执行`doSomethingUsefulOne`和`doSomethingUsefulTwo`并返回结果。由于`async`被定义为`coroutineScope`的扩展，因此我们需要将它放在作用域中：

```kotlin
suspend fun concurrentSum() = coroutineScope {
    val one = async { doSomethingUsefulOne() }
    val two = async { doSomethingUsefulTwo() }
    one.await() + two.await()
}
```

这样，如果`concurrentSum`函数的代码内部出现问题，并且抛出异常，则其范围内启动的所有协程都将被取消。

```kotlin
val time = measureTimeMillis {
    println("The answer is ${concurrentSum()}")
}
println("Completed in $time ms")
```

取消总是通过协程层次结构传播：

```kotlin
fun main(): Unit = runBlocking {
    try {
        failedConcurrentSum()
    } catch (e: ArithmeticException) {
        println("Computation failed with ArithmeticException")
    }
}

suspend fun failedConcurrentSum(): Int = coroutineScope {
    val one = async {
        try {
            delay(Long.MAX_VALUE)
            42
        } finally {
            println("First child was cancelled")
        }
    }
    val two = async<Int> {
        println("Second child throws an exception")
        throw ArithmeticException()
    }
    one.await() + two.await()
}

>>Second child throws an exception
>>First child was cancelled
>>Computation failed with ArithmeticException
```

